AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  An AWS lambda to automatically add SSM patch group tags

Metadata:
  AWS::ServerlessRepo::Application:
    Name: "lambda-tag-patch-group"
    Description: "An AWS lambda to automatically add SSM patch group tags"
    Author: "Sage-Bionetworks"
    SpdxLicenseId: "Apache-2.0"
    # paths are relative to .aws-sam/build directory
    LicenseUrl: "LICENSE"
    ReadmeUrl: "README.md"
    Labels: ["serverless", "ssm", "tags"]
    HomePageUrl: "https://github.com/Sage-Bionetworks-IT/lambda-tag-patch-group"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  TaggerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: tagger/app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt FunctionRole.Arn
      Events:
        Schedule:
          Type: Schedule # More info about Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#schedule
          Properties:
            Schedule: !Ref Schedule

  FunctionRole:   # execute lambda function with this role
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

Outputs:
  TaggerFunctionArn:
    Description: "Tagger Lambda Function ARN"
    Value: !GetAtt TaggerFunction.Arn
  TaggerFunctionRoleArn:
    Description: "Implicit IAM Role created for Tagger function"
    Value: !GetAtt FunctionRole.Arn
